In [ ]:
from plyer import notification
import requests
import pandas as pd
#from playsound import playsound

# Conexão API

In [118]:
url = ('https://brasilapi.com.br/api/ibge/uf/v1')
response = requests.get(url)
response

# Função alerta()

In [89]:
def alerta(response):
    if response.status_code != 200:
        try:
            response.raise_for_status()  
        except Exception as erro:
            notification.notify(
                title=f'Erro: Status {response.status_code}',
                message=f'{erro}',  
                timeout=10
            )

# Tabelas (Data)

In [119]:
if response.status_code == 200:
    data_json = response.json()
    print('Dados Recebidos!')
else:
    alerta(response)

Dados Recebidos!

In [121]:
# tabela 1 - contendo sigla do Estado, nome e detalhamento sobre região.

df_estados = pd.DataFrame(data_json)
df_estados

,id,sigla,nome,regiao
0,11,RO,Rondônia,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
1,12,AC,Acre,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
2,13,AM,Amazonas,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
3,14,RR,Roraima,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
4,15,PA,Pará,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
5,16,AP,Amapá,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
6,17,TO,Tocantins,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
7,21,MA,Maranhão,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
8,22,PI,Piauí,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
9,23,CE,Ceará,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
10,24,RN,Rio Grande do Norte,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
11,25,PB,Paraíba,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
12,26,PE,Pernambuco,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
13,27,AL,Alagoas,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
14,28,SE,Sergipe,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
15,29,BA,Bahia,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
16,31,MG,Minas Gerais,"{'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}"
17,32,ES,Espírito Santo,"{'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}"
18,33,RJ,Rio de Janeiro,"{'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}"
19,35,SP,São Paulo,"{'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}"
20,41,PR,Paraná,"{'id': 4, 'sigla': 'S', 'nome': 'Sul'}"
21,42,SC,Santa Catarina,"{'id': 4, 'sigla': 'S', 'nome': 'Sul'}"
22,43,RS,Rio Grande do Sul,"{'id': 4, 'sigla': 'S', 'nome': 'Sul'}"
23,50,MS,Mato Grosso do Sul,"{'id': 5, 'sigla': 'CO', 'nome': 'Centro-Oeste'}"
24,51,MT,Mato Grosso,"{'id': 5, 'sigla': 'CO', 'nome': 'Centro-Oeste'}"
25,52,GO,Goiás,"{'id': 5, 'sigla': 'CO', 'nome': 'Centro-Oeste'}"
26,53,DF,Distrito Federal,"{'id': 5, 'sigla': 'CO', 'nome': 'Centro-Oeste'}"

In [122]:
url = ('https://brasilapi.com.br/api/pix/v1/participants')
response = requests.get(url)
response

In [123]:
if response.status_code == 200:
    data_json = response.json()
    print('Dados Recebidos!')
else:
    alerta(response)

Dados Recebidos!

In [124]:
# Table 2 - contendo informações de transações realizadas via pix
df_pix = pd.DataFrame(data_json)
df_pix

,ispb,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,2020-11-03T09:30:00.000Z
3,00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,2020-11-03T09:30:00.000Z
4,00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,2020-11-03T09:30:00.000Z
...,...,...,...,...,...,...
825,95213211,"COOPERATIVA DE CRéDITO, POUPANçA E INVESTIMENT...",COOP SICREDI CAMINHO DAS ÁGUAS RS,PDCT,IDRT,2020-11-03T09:30:00.000Z
826,95424891,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI VALE DO RIO PARDO,PDCT,IDRT,2020-11-03T09:30:00.000Z
827,95594941,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI REG CENTRO RS/MG,PDCT,IDRT,2020-11-03T09:30:00.000Z
828,97259253,COOPERATIVA E ECONOMIA E CRÉDITO MÚTUO DOS MÉD...,CECM MÉDICOS PLANALTO MÉDIO RS - CREDISIS/CRED...,PDCT,IDRT,2021-10-04T12:53:10.567Z
829,97489280,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI INTEGRAÇÃO BAHIA,PDCT,IDRT,2020-11-03T09:30:00.000Z

In [125]:
url = ('https://brasilapi.com.br/api/cvm/corretoras/v1')
response = requests.get(url)
response

In [126]:
if response.status_code == 200:
    data_json = response.json()
    print('Dados Recebidos!')
else:
    alerta(response)

Dados Recebidos!

In [127]:
# Table 3 - Dados de corretoras no BR
df_corretora = pd.DataFrame(data_json)
df_corretora

,cnpj,type,nome_social,nome_comercial,status,email,telefone,cep,pais,uf,municipio,bairro,complemento,logradouro,data_patrimonio_liquido,valor_patrimonio_liquido,codigo_cvm,data_inicio_situacao,data_registro
0,76621457000185,CORRETORAS,4UM DTVM S.A.,4UM INVESTIMENTOS,CANCELADA,controle@4um.com.br,33519966,80420210,BRASIL,PR,CURITIBA,CENTRO,4º ANDAR,R. VISCONDE DO RIO BRANCO 1488,2005-12-31,4228660.18,2275,2006-10-05,1968-01-15
1,33817677000176,CORRETORAS,ABC BRASIL DISTRIBUIDORA DE TÍTULOS E VALORES ...,ABC BRASIL DTVM,CANCELADA,complianceregulatorio@abcbrasil.com.br,31702172,1453000,,SP,SÃO PAULO,ITAIM BIBI,2º ANDAR,"AV. CIDADE JARDIM, 803",2002-12-31,0.00,3514,2002-10-14,2002-10-14
2,10664027000132,CORRETORAS,ABERTURA CCVM LTDA,ABERTURA CCVM LTDA,CANCELADA,,,50010240,BRASIL,PE,RECIFE,,,R DO IMP.D.PEDRO II 239/CJ.102,1989-12-31,5995252.29,329,1990-06-12,1986-07-08
3,44527444000155,CORRETORAS,ABN AMRO CLEARING CORRETORA DE T-TULOS E VALOR...,,EM FUNCIONAMENTO NORMAL,canal.comunicacao@br.abnamro.com,30737417,4551010,,SP,SÃO PAULO,VILA OLIMPIA,"11¦ ANDAR, CJ. 111","RUA FIDÛNCIO RAMOS, N¦ 302, TORRE B",2023-12-31,11122779.75,3794,2022-06-20,2022-06-20
4,33819590000138,CORRETORAS,AÇÃO S.A. CORRETORA DE VALORES E CÂMBIO,ACAO SA CVC,CANCELADA,,5095755,20040040,BRASIL,RJ,RIO DE JANEIRO,CENTRO,,"PRAÇA OLAVO BILAC, 28/ SL. 608",2000-12-31,291862.38,1112,2001-04-11,1968-04-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,01170892000131,CORRETORAS,VOTORANTIM CTVM LTDA,VOTORANTIM,CANCELADA,demandasregulatorias@bancovotorantim.com.br,51711894,4794000,BRASIL,SP,SÃO PAULO,VL.GERTRUDES,TORRE A-14º ANDAR,"AV DAS NAÇÕES UNIDAS, 14.171",2017-12-31,266791832.77,3166,2018-08-27,1996-03-15
370,61769790000169,CORRETORAS,WALPIRES S/A CCTVM,WALPIRES S/A CCTVM,CANCELADA,andre@walpires.com.br,28087065,1452002,BRASIL,SP,SÃO PAULO,JARDIM PAULISTANO,1309 - 9ºANDAR,AVENIDA BRIGADEIRO FARIA LIMA,2017-12-31,7464373.90,1902,2019-09-24,1967-09-20
371,92875780000131,CORRETORAS,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,WARREN CORRETORA,EM FUNCIONAMENTO NORMAL,juridico@warren.com.br,32372273,90035191,,RS,PORTO ALEGRE,BOM FIM,2º ANDAR,"AVENIDA OSVALDO ARANHA, 720",2023-12-31,20672910.31,2534,1967-12-06,1967-12-06
372,24543688000114,CORRETORAS,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...,PERFIL,CANCELADA,,2249022,52061540,BRASIL,PE,RECIFE,CASA FORTE,,"AV.17 DE AGOSTO,2579",1996-12-31,608260.02,2658,1997-02-21,1989-11-14
373,02332886000104,CORRETORAS,XP INVESTIMENTOS CCTVM S.A.,XP INVESTIMENTOS,EM FUNCIONAMENTO NORMAL,fabricio.almeida@xpi.com.br,30272237,22440032,,RJ,RIO DE JANEIRO,LEBLON,5º ANDAR,AVENIDA ATAULFO DE PAIVA 153,2023-12-31,8405739266.66,3247,1998-02-10,1997-12-05